apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: litewebservices-portal-ingress
  namespace: {{.Release.Namespace}}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{.Values.ingress.issuer}}
spec:
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: lws-tls
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix 
            backend:
              service:
                name: chart-paper-server
                port:
                  number: 8000
          
